{{- if .Values.ingress.http.enabled -}}
{{ template "feast.ingress" (list . "jobservice" "http" .Values.ingress.http) }}
{{- end }}
---
{{ if .Values.ingress.grpc.enabled -}}
{{ template "feast.ingress" (list . "jobservice" "grpc" .Values.ingress.grpc) }}
{{- end }}
