presubmits:
- name: test-end-to-end-gcp
  decorate: true
  always_run: true
  max_concurrency: 1
  spec:
    containers:
    - image: gcr.io/kf-feast/feast-ci:latest
      command: [ "infra/scripts/test-end-to-end-gcp.sh" ]
      resources:
        requests:
          cpu: "6"
          memory: "6144Mi"
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcloud/service-account.json
      volumeMounts:
        - mountPath: /etc/gcloud/service-account.json
          name: service-account
          readOnly: true
          subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account
- name: test-end-to-end-aws
  decorate: true
  always_run: true
  max_concurrency: 1
  spec:
    containers:
      - image: gcr.io/kf-feast/feast-ci:latest
        command: [ "infra/scripts/aws-runner.sh", "--location-from-prow", "--project-name", "feast-ci-project"  ]
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcloud/service-account.json
          - name: DOCKER_REPOSITORY
            value: gcr.io/kf-feast
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: feast-aws-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: feast-aws-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            value: us-west-2
        volumeMounts:
          - mountPath: /etc/gcloud/service-account.json
            name: service-account
            readOnly: true
            subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account
- name: test-end-to-end-sparkop
  decorate: true
  always_run: true
  max_concurrency: 1
  spec:
    metadata:
      namespace: sparkop-e2e
    containers:
      - image: gcr.io/kf-feast/feast-ci:latest
        command: [ "infra/scripts/test-end-to-end-sparkop.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcloud/service-account.json
          - name: DOCKER_REPOSITORY
            value: gcr.io/kf-feast
        volumeMounts:
          - mountPath: /etc/gcloud/service-account.json
            name: service-account
            readOnly: true
            subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account


#- name: test-end-to-end-azure
#  decorate: true
#  always_run: true
#  max_concurrency: 1
#  spec:
#    containers:
#    - image: gcr.io/kf-feast/feast-ci:develop
#      command: [ "infra/scripts/azure-runner.sh" ]
#      resources:
#        requests:
#          cpu: "2"
#          memory: "2048Mi"
#      env:
#        - name: GOOGLE_APPLICATION_CREDENTIALS
#          value: /etc/gcloud/service-account.json
#        - name: RESOURCE_GROUP
#          value: Feast
#        - name: AKS_CLUSTER_NAME
#          value: main
#        - name: DOCKER_REPOSITORY
#          value: gcr.io/kf-feast
#        - name: STAGING_PATH
#          value: wasbs://staging@feastcicd.blob.core.windows.net/cicd-staging
#        - name: AZ_SERVICE_PRINCIPAL_ID
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZ_SERVICE_PRINCIPAL_ID
#        - name: AZ_SERVICE_PRINCIPAL_PASS
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZ_SERVICE_PRINCIPAL_PASS
#        - name: AZ_SERVICE_PRINCIPAL_TENANT_ID
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZ_SERVICE_PRINCIPAL_TENANT_ID
#        - name: AZURE_BLOB_ACCOUNT_NAME
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZURE_BLOB_ACCOUNT_NAME
#        - name: AZURE_BLOB_ACCOUNT_ACCESS_KEY
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZURE_BLOB_ACCOUNT_ACCESS_KEY
#      volumeMounts:
#        - mountPath: /etc/gcloud/service-account.json
#          name: service-account
#          readOnly: true
#          subPath: service-account.json
#    volumes:
#      - name: service-account
#        secret:
#          secretName: feast-service-account

postsubmits:
- name: test-end-to-end-gcp
  decorate: true
  always_run: true
  max_concurrency: 1
  branches:
    - ^master$
  spec:
    containers:
    - image: gcr.io/kf-feast/feast-ci:latest
      command: [ "infra/scripts/test-end-to-end-gcp.sh" ]
      resources:
        requests:
          cpu: "6"
          memory: "6144Mi"
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcloud/service-account.json
      volumeMounts:
        - mountPath: /etc/gcloud/service-account.json
          name: service-account
          readOnly: true
          subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account

- name: test-end-to-end-aws
  decorate: true
  always_run: true
  max_concurrency: 1
  branches:
    - ^master$
  spec:
    containers:
      - image: gcr.io/kf-feast/feast-ci:latest
        command: [ "infra/scripts/aws-runner.sh", "--location-from-prow", "--project-name", "feast-ci-project" ]
        resources:
          requests:
            cpu: "2"
            memory: "2048Mi"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcloud/service-account.json
          - name: DOCKER_REPOSITORY
            value: gcr.io/kf-feast
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: feast-aws-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: feast-aws-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            value: us-west-2
        volumeMounts:
          - mountPath: /etc/gcloud/service-account.json
            name: service-account
            readOnly: true
            subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account

- name: test-end-to-end-sparkop
  decorate: true
  always_run: true
  max_concurrency: 1
  branches:
    - ^master$
  spec:
    metadata:
      namespace: sparkop-e2e
    containers:
      - image: gcr.io/kf-feast/feast-ci:latest
        command: [ "infra/scripts/test-end-to-end-sparkop.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "2048Mi"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcloud/service-account.json
          - name: DOCKER_REPOSITORY
            value: gcr.io/kf-feast
        volumeMounts:
          - mountPath: /etc/gcloud/service-account.json
            name: service-account
            readOnly: true
            subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account

#- name: test-end-to-end-azure
#  decorate: true
#  always_run: true
#  max_concurrency: 1
#  branches:
#    - ^master$
#  spec:
#    containers:
#    - image: gcr.io/kf-feast/feast-ci:develop
#      command: [ "infra/scripts/azure-runner.sh" ]
#      resources:
#        requests:
#          cpu: "2"
#          memory: "2048Mi"
#      env:
#        - name: GOOGLE_APPLICATION_CREDENTIALS
#          value: /etc/gcloud/service-account.json
#        - name: RESOURCE_GROUP
#          value: Feast
#        - name: AKS_CLUSTER_NAME
#          value: main
#        - name: DOCKER_REPOSITORY
#          value: gcr.io/kf-feast
#        - name: STAGING_PATH
#          value: wasbs://staging@feastcicd.blob.core.windows.net/cicd-staging
#        - name: AZ_SERVICE_PRINCIPAL_ID
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZ_SERVICE_PRINCIPAL_ID
#        - name: AZ_SERVICE_PRINCIPAL_PASS
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZ_SERVICE_PRINCIPAL_PASS
#        - name: AZ_SERVICE_PRINCIPAL_TENANT_ID
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZ_SERVICE_PRINCIPAL_TENANT_ID
#        - name: AZURE_BLOB_ACCOUNT_NAME
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZURE_BLOB_ACCOUNT_NAME
#        - name: AZURE_BLOB_ACCOUNT_ACCESS_KEY
#          valueFrom:
#            secretKeyRef:
#              name: feast-az-creds
#              key: AZURE_BLOB_ACCOUNT_ACCESS_KEY
#      volumeMounts:
#        - mountPath: /etc/gcloud/service-account.json
#          name: service-account
#          readOnly: true
#          subPath: service-account.json
#    volumes:
#      - name: service-account
#        secret:
#          secretName: feast-service-account