version: 2

sphinx:
   configuration: python/docs/source/conf.py

formats:
   - pdf

python:
  version: 3.7
  install:
      - requirements: python/requirements-ci.txt
      - path: python/
        method: setuptools