// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

/**
 * Protobuf type {@code com.example.AllTypesMessage}
 */
public final class AllTypesMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.AllTypesMessage)
    AllTypesMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllTypesMessage.newBuilder() to construct.
  private AllTypesMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllTypesMessage() {
    string_ = "";
    bytes_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AllTypesMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllTypesMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            double_ = input.readDouble();
            break;
          }
          case 21: {

            float_ = input.readFloat();
            break;
          }
          case 24: {

            integer_ = input.readInt32();
            break;
          }
          case 32: {

            long_ = input.readInt64();
            break;
          }
          case 40: {

            uinteger_ = input.readUInt32();
            break;
          }
          case 48: {

            ulong_ = input.readUInt64();
            break;
          }
          case 56: {

            sinteger_ = input.readSInt32();
            break;
          }
          case 64: {

            slong_ = input.readSInt64();
            break;
          }
          case 77: {

            finteger_ = input.readFixed32();
            break;
          }
          case 81: {

            flong_ = input.readFixed64();
            break;
          }
          case 93: {

            sfinteger_ = input.readSFixed32();
            break;
          }
          case 105: {

            sflong_ = input.readSFixed64();
            break;
          }
          case 112: {

            bool_ = input.readBool();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            string_ = s;
            break;
          }
          case 130: {

            bytes_ = input.readBytes();
            break;
          }
          case 138: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              map_ = com.google.protobuf.MapField.newMapField(
                  MapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            map__ = input.readMessage(
                MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            map_.getMutableMap().put(
                map__.getKey(), map__.getValue());
            break;
          }
          case 146: {
            com.example.protos.InnerMessage.Builder subBuilder = null;
            if (inner_ != null) {
              subBuilder = inner_.toBuilder();
            }
            inner_ = input.readMessage(com.example.protos.InnerMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(inner_);
              inner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 154: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (eventTimestamp_ != null) {
              subBuilder = eventTimestamp_.toBuilder();
            }
            eventTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eventTimestamp_);
              eventTimestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protos.Source.internal_static_com_example_AllTypesMessage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 17:
        return internalGetMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protos.Source.internal_static_com_example_AllTypesMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protos.AllTypesMessage.class, com.example.protos.AllTypesMessage.Builder.class);
  }

  public static final int DOUBLE_FIELD_NUMBER = 1;
  private double double_;
  /**
   * <code>double double = 1;</code>
   * @return The double.
   */
  @java.lang.Override
  public double getDouble() {
    return double_;
  }

  public static final int FLOAT_FIELD_NUMBER = 2;
  private float float_;
  /**
   * <code>float float = 2;</code>
   * @return The float.
   */
  @java.lang.Override
  public float getFloat() {
    return float_;
  }

  public static final int INTEGER_FIELD_NUMBER = 3;
  private int integer_;
  /**
   * <code>int32 integer = 3;</code>
   * @return The integer.
   */
  @java.lang.Override
  public int getInteger() {
    return integer_;
  }

  public static final int LONG_FIELD_NUMBER = 4;
  private long long_;
  /**
   * <code>int64 long = 4;</code>
   * @return The long.
   */
  @java.lang.Override
  public long getLong() {
    return long_;
  }

  public static final int UINTEGER_FIELD_NUMBER = 5;
  private int uinteger_;
  /**
   * <code>uint32 uinteger = 5;</code>
   * @return The uinteger.
   */
  @java.lang.Override
  public int getUinteger() {
    return uinteger_;
  }

  public static final int ULONG_FIELD_NUMBER = 6;
  private long ulong_;
  /**
   * <code>uint64 ulong = 6;</code>
   * @return The ulong.
   */
  @java.lang.Override
  public long getUlong() {
    return ulong_;
  }

  public static final int SINTEGER_FIELD_NUMBER = 7;
  private int sinteger_;
  /**
   * <code>sint32 sinteger = 7;</code>
   * @return The sinteger.
   */
  @java.lang.Override
  public int getSinteger() {
    return sinteger_;
  }

  public static final int SLONG_FIELD_NUMBER = 8;
  private long slong_;
  /**
   * <code>sint64 slong = 8;</code>
   * @return The slong.
   */
  @java.lang.Override
  public long getSlong() {
    return slong_;
  }

  public static final int FINTEGER_FIELD_NUMBER = 9;
  private int finteger_;
  /**
   * <code>fixed32 finteger = 9;</code>
   * @return The finteger.
   */
  @java.lang.Override
  public int getFinteger() {
    return finteger_;
  }

  public static final int FLONG_FIELD_NUMBER = 10;
  private long flong_;
  /**
   * <code>fixed64 flong = 10;</code>
   * @return The flong.
   */
  @java.lang.Override
  public long getFlong() {
    return flong_;
  }

  public static final int SFINTEGER_FIELD_NUMBER = 11;
  private int sfinteger_;
  /**
   * <code>sfixed32 sfinteger = 11;</code>
   * @return The sfinteger.
   */
  @java.lang.Override
  public int getSfinteger() {
    return sfinteger_;
  }

  public static final int SFLONG_FIELD_NUMBER = 13;
  private long sflong_;
  /**
   * <code>sfixed64 sflong = 13;</code>
   * @return The sflong.
   */
  @java.lang.Override
  public long getSflong() {
    return sflong_;
  }

  public static final int BOOL_FIELD_NUMBER = 14;
  private boolean bool_;
  /**
   * <code>bool bool = 14;</code>
   * @return The bool.
   */
  @java.lang.Override
  public boolean getBool() {
    return bool_;
  }

  public static final int STRING_FIELD_NUMBER = 15;
  private volatile java.lang.Object string_;
  /**
   * <code>string string = 15;</code>
   * @return The string.
   */
  @java.lang.Override
  public java.lang.String getString() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      string_ = s;
      return s;
    }
  }
  /**
   * <code>string string = 15;</code>
   * @return The bytes for string.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = string_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      string_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTES_FIELD_NUMBER = 16;
  private com.google.protobuf.ByteString bytes_;
  /**
   * <code>bytes bytes = 16;</code>
   * @return The bytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytes() {
    return bytes_;
  }

  public static final int MAP_FIELD_NUMBER = 17;
  private static final class MapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.example.protos.Source.internal_static_com_example_AllTypesMessage_MapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> map_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMap() {
    if (map_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapDefaultEntryHolder.defaultEntry);
    }
    return map_;
  }

  public int getMapCount() {
    return internalGetMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */

  @java.lang.Override
  public boolean containsMap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMap() {
    return getMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
    return internalGetMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */
  @java.lang.Override

  public java.lang.String getMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */
  @java.lang.Override

  public java.lang.String getMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INNER_FIELD_NUMBER = 18;
  private com.example.protos.InnerMessage inner_;
  /**
   * <code>.com.example.InnerMessage inner = 18;</code>
   * @return Whether the inner field is set.
   */
  @java.lang.Override
  public boolean hasInner() {
    return inner_ != null;
  }
  /**
   * <code>.com.example.InnerMessage inner = 18;</code>
   * @return The inner.
   */
  @java.lang.Override
  public com.example.protos.InnerMessage getInner() {
    return inner_ == null ? com.example.protos.InnerMessage.getDefaultInstance() : inner_;
  }
  /**
   * <code>.com.example.InnerMessage inner = 18;</code>
   */
  @java.lang.Override
  public com.example.protos.InnerMessageOrBuilder getInnerOrBuilder() {
    return getInner();
  }

  public static final int EVENT_TIMESTAMP_FIELD_NUMBER = 19;
  private com.google.protobuf.Timestamp eventTimestamp_;
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
   * @return Whether the eventTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasEventTimestamp() {
    return eventTimestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
   * @return The eventTimestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEventTimestamp() {
    return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
    return getEventTimestamp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (double_ != 0D) {
      output.writeDouble(1, double_);
    }
    if (float_ != 0F) {
      output.writeFloat(2, float_);
    }
    if (integer_ != 0) {
      output.writeInt32(3, integer_);
    }
    if (long_ != 0L) {
      output.writeInt64(4, long_);
    }
    if (uinteger_ != 0) {
      output.writeUInt32(5, uinteger_);
    }
    if (ulong_ != 0L) {
      output.writeUInt64(6, ulong_);
    }
    if (sinteger_ != 0) {
      output.writeSInt32(7, sinteger_);
    }
    if (slong_ != 0L) {
      output.writeSInt64(8, slong_);
    }
    if (finteger_ != 0) {
      output.writeFixed32(9, finteger_);
    }
    if (flong_ != 0L) {
      output.writeFixed64(10, flong_);
    }
    if (sfinteger_ != 0) {
      output.writeSFixed32(11, sfinteger_);
    }
    if (sflong_ != 0L) {
      output.writeSFixed64(13, sflong_);
    }
    if (bool_ != false) {
      output.writeBool(14, bool_);
    }
    if (!getStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, string_);
    }
    if (!bytes_.isEmpty()) {
      output.writeBytes(16, bytes_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMap(),
        MapDefaultEntryHolder.defaultEntry,
        17);
    if (inner_ != null) {
      output.writeMessage(18, getInner());
    }
    if (eventTimestamp_ != null) {
      output.writeMessage(19, getEventTimestamp());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (double_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, double_);
    }
    if (float_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, float_);
    }
    if (integer_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, integer_);
    }
    if (long_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, long_);
    }
    if (uinteger_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, uinteger_);
    }
    if (ulong_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, ulong_);
    }
    if (sinteger_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(7, sinteger_);
    }
    if (slong_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(8, slong_);
    }
    if (finteger_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(9, finteger_);
    }
    if (flong_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(10, flong_);
    }
    if (sfinteger_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed32Size(11, sfinteger_);
    }
    if (sflong_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed64Size(13, sflong_);
    }
    if (bool_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, bool_);
    }
    if (!getStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, string_);
    }
    if (!bytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(16, bytes_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, map__);
    }
    if (inner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(18, getInner());
    }
    if (eventTimestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, getEventTimestamp());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protos.AllTypesMessage)) {
      return super.equals(obj);
    }
    com.example.protos.AllTypesMessage other = (com.example.protos.AllTypesMessage) obj;

    if (java.lang.Double.doubleToLongBits(getDouble())
        != java.lang.Double.doubleToLongBits(
            other.getDouble())) return false;
    if (java.lang.Float.floatToIntBits(getFloat())
        != java.lang.Float.floatToIntBits(
            other.getFloat())) return false;
    if (getInteger()
        != other.getInteger()) return false;
    if (getLong()
        != other.getLong()) return false;
    if (getUinteger()
        != other.getUinteger()) return false;
    if (getUlong()
        != other.getUlong()) return false;
    if (getSinteger()
        != other.getSinteger()) return false;
    if (getSlong()
        != other.getSlong()) return false;
    if (getFinteger()
        != other.getFinteger()) return false;
    if (getFlong()
        != other.getFlong()) return false;
    if (getSfinteger()
        != other.getSfinteger()) return false;
    if (getSflong()
        != other.getSflong()) return false;
    if (getBool()
        != other.getBool()) return false;
    if (!getString()
        .equals(other.getString())) return false;
    if (!getBytes()
        .equals(other.getBytes())) return false;
    if (!internalGetMap().equals(
        other.internalGetMap())) return false;
    if (hasInner() != other.hasInner()) return false;
    if (hasInner()) {
      if (!getInner()
          .equals(other.getInner())) return false;
    }
    if (hasEventTimestamp() != other.hasEventTimestamp()) return false;
    if (hasEventTimestamp()) {
      if (!getEventTimestamp()
          .equals(other.getEventTimestamp())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDouble()));
    hash = (37 * hash) + FLOAT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloat());
    hash = (37 * hash) + INTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getInteger();
    hash = (37 * hash) + LONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLong());
    hash = (37 * hash) + UINTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getUinteger();
    hash = (37 * hash) + ULONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUlong());
    hash = (37 * hash) + SINTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getSinteger();
    hash = (37 * hash) + SLONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSlong());
    hash = (37 * hash) + FINTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getFinteger();
    hash = (37 * hash) + FLONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFlong());
    hash = (37 * hash) + SFINTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getSfinteger();
    hash = (37 * hash) + SFLONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSflong());
    hash = (37 * hash) + BOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBool());
    hash = (37 * hash) + STRING_FIELD_NUMBER;
    hash = (53 * hash) + getString().hashCode();
    hash = (37 * hash) + BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getBytes().hashCode();
    if (!internalGetMap().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMap().hashCode();
    }
    if (hasInner()) {
      hash = (37 * hash) + INNER_FIELD_NUMBER;
      hash = (53 * hash) + getInner().hashCode();
    }
    if (hasEventTimestamp()) {
      hash = (37 * hash) + EVENT_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getEventTimestamp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protos.AllTypesMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.AllTypesMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.AllTypesMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.AllTypesMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.protos.AllTypesMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.AllTypesMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protos.AllTypesMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.AllTypesMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.AllTypesMessage)
      com.example.protos.AllTypesMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protos.Source.internal_static_com_example_AllTypesMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 17:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 17:
          return internalGetMutableMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protos.Source.internal_static_com_example_AllTypesMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protos.AllTypesMessage.class, com.example.protos.AllTypesMessage.Builder.class);
    }

    // Construct using com.example.protos.AllTypesMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      double_ = 0D;

      float_ = 0F;

      integer_ = 0;

      long_ = 0L;

      uinteger_ = 0;

      ulong_ = 0L;

      sinteger_ = 0;

      slong_ = 0L;

      finteger_ = 0;

      flong_ = 0L;

      sfinteger_ = 0;

      sflong_ = 0L;

      bool_ = false;

      string_ = "";

      bytes_ = com.google.protobuf.ByteString.EMPTY;

      internalGetMutableMap().clear();
      if (innerBuilder_ == null) {
        inner_ = null;
      } else {
        inner_ = null;
        innerBuilder_ = null;
      }
      if (eventTimestampBuilder_ == null) {
        eventTimestamp_ = null;
      } else {
        eventTimestamp_ = null;
        eventTimestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protos.Source.internal_static_com_example_AllTypesMessage_descriptor;
    }

    @java.lang.Override
    public com.example.protos.AllTypesMessage getDefaultInstanceForType() {
      return com.example.protos.AllTypesMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protos.AllTypesMessage build() {
      com.example.protos.AllTypesMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protos.AllTypesMessage buildPartial() {
      com.example.protos.AllTypesMessage result = new com.example.protos.AllTypesMessage(this);
      int from_bitField0_ = bitField0_;
      result.double_ = double_;
      result.float_ = float_;
      result.integer_ = integer_;
      result.long_ = long_;
      result.uinteger_ = uinteger_;
      result.ulong_ = ulong_;
      result.sinteger_ = sinteger_;
      result.slong_ = slong_;
      result.finteger_ = finteger_;
      result.flong_ = flong_;
      result.sfinteger_ = sfinteger_;
      result.sflong_ = sflong_;
      result.bool_ = bool_;
      result.string_ = string_;
      result.bytes_ = bytes_;
      result.map_ = internalGetMap();
      result.map_.makeImmutable();
      if (innerBuilder_ == null) {
        result.inner_ = inner_;
      } else {
        result.inner_ = innerBuilder_.build();
      }
      if (eventTimestampBuilder_ == null) {
        result.eventTimestamp_ = eventTimestamp_;
      } else {
        result.eventTimestamp_ = eventTimestampBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protos.AllTypesMessage) {
        return mergeFrom((com.example.protos.AllTypesMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protos.AllTypesMessage other) {
      if (other == com.example.protos.AllTypesMessage.getDefaultInstance()) return this;
      if (other.getDouble() != 0D) {
        setDouble(other.getDouble());
      }
      if (other.getFloat() != 0F) {
        setFloat(other.getFloat());
      }
      if (other.getInteger() != 0) {
        setInteger(other.getInteger());
      }
      if (other.getLong() != 0L) {
        setLong(other.getLong());
      }
      if (other.getUinteger() != 0) {
        setUinteger(other.getUinteger());
      }
      if (other.getUlong() != 0L) {
        setUlong(other.getUlong());
      }
      if (other.getSinteger() != 0) {
        setSinteger(other.getSinteger());
      }
      if (other.getSlong() != 0L) {
        setSlong(other.getSlong());
      }
      if (other.getFinteger() != 0) {
        setFinteger(other.getFinteger());
      }
      if (other.getFlong() != 0L) {
        setFlong(other.getFlong());
      }
      if (other.getSfinteger() != 0) {
        setSfinteger(other.getSfinteger());
      }
      if (other.getSflong() != 0L) {
        setSflong(other.getSflong());
      }
      if (other.getBool() != false) {
        setBool(other.getBool());
      }
      if (!other.getString().isEmpty()) {
        string_ = other.string_;
        onChanged();
      }
      if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
        setBytes(other.getBytes());
      }
      internalGetMutableMap().mergeFrom(
          other.internalGetMap());
      if (other.hasInner()) {
        mergeInner(other.getInner());
      }
      if (other.hasEventTimestamp()) {
        mergeEventTimestamp(other.getEventTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.protos.AllTypesMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.protos.AllTypesMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private double double_ ;
    /**
     * <code>double double = 1;</code>
     * @return The double.
     */
    @java.lang.Override
    public double getDouble() {
      return double_;
    }
    /**
     * <code>double double = 1;</code>
     * @param value The double to set.
     * @return This builder for chaining.
     */
    public Builder setDouble(double value) {
      
      double_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double double = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDouble() {
      
      double_ = 0D;
      onChanged();
      return this;
    }

    private float float_ ;
    /**
     * <code>float float = 2;</code>
     * @return The float.
     */
    @java.lang.Override
    public float getFloat() {
      return float_;
    }
    /**
     * <code>float float = 2;</code>
     * @param value The float to set.
     * @return This builder for chaining.
     */
    public Builder setFloat(float value) {
      
      float_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float float = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat() {
      
      float_ = 0F;
      onChanged();
      return this;
    }

    private int integer_ ;
    /**
     * <code>int32 integer = 3;</code>
     * @return The integer.
     */
    @java.lang.Override
    public int getInteger() {
      return integer_;
    }
    /**
     * <code>int32 integer = 3;</code>
     * @param value The integer to set.
     * @return This builder for chaining.
     */
    public Builder setInteger(int value) {
      
      integer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 integer = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteger() {
      
      integer_ = 0;
      onChanged();
      return this;
    }

    private long long_ ;
    /**
     * <code>int64 long = 4;</code>
     * @return The long.
     */
    @java.lang.Override
    public long getLong() {
      return long_;
    }
    /**
     * <code>int64 long = 4;</code>
     * @param value The long to set.
     * @return This builder for chaining.
     */
    public Builder setLong(long value) {
      
      long_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 long = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLong() {
      
      long_ = 0L;
      onChanged();
      return this;
    }

    private int uinteger_ ;
    /**
     * <code>uint32 uinteger = 5;</code>
     * @return The uinteger.
     */
    @java.lang.Override
    public int getUinteger() {
      return uinteger_;
    }
    /**
     * <code>uint32 uinteger = 5;</code>
     * @param value The uinteger to set.
     * @return This builder for chaining.
     */
    public Builder setUinteger(int value) {
      
      uinteger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uinteger = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUinteger() {
      
      uinteger_ = 0;
      onChanged();
      return this;
    }

    private long ulong_ ;
    /**
     * <code>uint64 ulong = 6;</code>
     * @return The ulong.
     */
    @java.lang.Override
    public long getUlong() {
      return ulong_;
    }
    /**
     * <code>uint64 ulong = 6;</code>
     * @param value The ulong to set.
     * @return This builder for chaining.
     */
    public Builder setUlong(long value) {
      
      ulong_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ulong = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUlong() {
      
      ulong_ = 0L;
      onChanged();
      return this;
    }

    private int sinteger_ ;
    /**
     * <code>sint32 sinteger = 7;</code>
     * @return The sinteger.
     */
    @java.lang.Override
    public int getSinteger() {
      return sinteger_;
    }
    /**
     * <code>sint32 sinteger = 7;</code>
     * @param value The sinteger to set.
     * @return This builder for chaining.
     */
    public Builder setSinteger(int value) {
      
      sinteger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 sinteger = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSinteger() {
      
      sinteger_ = 0;
      onChanged();
      return this;
    }

    private long slong_ ;
    /**
     * <code>sint64 slong = 8;</code>
     * @return The slong.
     */
    @java.lang.Override
    public long getSlong() {
      return slong_;
    }
    /**
     * <code>sint64 slong = 8;</code>
     * @param value The slong to set.
     * @return This builder for chaining.
     */
    public Builder setSlong(long value) {
      
      slong_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint64 slong = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlong() {
      
      slong_ = 0L;
      onChanged();
      return this;
    }

    private int finteger_ ;
    /**
     * <code>fixed32 finteger = 9;</code>
     * @return The finteger.
     */
    @java.lang.Override
    public int getFinteger() {
      return finteger_;
    }
    /**
     * <code>fixed32 finteger = 9;</code>
     * @param value The finteger to set.
     * @return This builder for chaining.
     */
    public Builder setFinteger(int value) {
      
      finteger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 finteger = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinteger() {
      
      finteger_ = 0;
      onChanged();
      return this;
    }

    private long flong_ ;
    /**
     * <code>fixed64 flong = 10;</code>
     * @return The flong.
     */
    @java.lang.Override
    public long getFlong() {
      return flong_;
    }
    /**
     * <code>fixed64 flong = 10;</code>
     * @param value The flong to set.
     * @return This builder for chaining.
     */
    public Builder setFlong(long value) {
      
      flong_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 flong = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlong() {
      
      flong_ = 0L;
      onChanged();
      return this;
    }

    private int sfinteger_ ;
    /**
     * <code>sfixed32 sfinteger = 11;</code>
     * @return The sfinteger.
     */
    @java.lang.Override
    public int getSfinteger() {
      return sfinteger_;
    }
    /**
     * <code>sfixed32 sfinteger = 11;</code>
     * @param value The sfinteger to set.
     * @return This builder for chaining.
     */
    public Builder setSfinteger(int value) {
      
      sfinteger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed32 sfinteger = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfinteger() {
      
      sfinteger_ = 0;
      onChanged();
      return this;
    }

    private long sflong_ ;
    /**
     * <code>sfixed64 sflong = 13;</code>
     * @return The sflong.
     */
    @java.lang.Override
    public long getSflong() {
      return sflong_;
    }
    /**
     * <code>sfixed64 sflong = 13;</code>
     * @param value The sflong to set.
     * @return This builder for chaining.
     */
    public Builder setSflong(long value) {
      
      sflong_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed64 sflong = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearSflong() {
      
      sflong_ = 0L;
      onChanged();
      return this;
    }

    private boolean bool_ ;
    /**
     * <code>bool bool = 14;</code>
     * @return The bool.
     */
    @java.lang.Override
    public boolean getBool() {
      return bool_;
    }
    /**
     * <code>bool bool = 14;</code>
     * @param value The bool to set.
     * @return This builder for chaining.
     */
    public Builder setBool(boolean value) {
      
      bool_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearBool() {
      
      bool_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object string_ = "";
    /**
     * <code>string string = 15;</code>
     * @return The string.
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string = 15;</code>
     * @return The bytes for string.
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string = 15;</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      string_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      
      string_ = getDefaultInstance().getString();
      onChanged();
      return this;
    }
    /**
     * <code>string string = 15;</code>
     * @param value The bytes for string to set.
     * @return This builder for chaining.
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      string_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes = 16;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }
    /**
     * <code>bytes bytes = 16;</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {
      
      bytes_ = getDefaultInstance().getBytes();
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMap() {
      onChanged();;
      if (map_ == null) {
        map_ = com.google.protobuf.MapField.newMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      if (!map_.isMutable()) {
        map_ = map_.copy();
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */

    @java.lang.Override
    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */
    @java.lang.Override

    public java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */
    @java.lang.Override

    public java.lang.String getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMap() {
      internalGetMutableMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */

    public Builder removeMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMap() {
      return internalGetMutableMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */
    public Builder putMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; map = 17;</code>
     */

    public Builder putAllMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.example.protos.InnerMessage inner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.protos.InnerMessage, com.example.protos.InnerMessage.Builder, com.example.protos.InnerMessageOrBuilder> innerBuilder_;
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     * @return Whether the inner field is set.
     */
    public boolean hasInner() {
      return innerBuilder_ != null || inner_ != null;
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     * @return The inner.
     */
    public com.example.protos.InnerMessage getInner() {
      if (innerBuilder_ == null) {
        return inner_ == null ? com.example.protos.InnerMessage.getDefaultInstance() : inner_;
      } else {
        return innerBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    public Builder setInner(com.example.protos.InnerMessage value) {
      if (innerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inner_ = value;
        onChanged();
      } else {
        innerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    public Builder setInner(
        com.example.protos.InnerMessage.Builder builderForValue) {
      if (innerBuilder_ == null) {
        inner_ = builderForValue.build();
        onChanged();
      } else {
        innerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    public Builder mergeInner(com.example.protos.InnerMessage value) {
      if (innerBuilder_ == null) {
        if (inner_ != null) {
          inner_ =
            com.example.protos.InnerMessage.newBuilder(inner_).mergeFrom(value).buildPartial();
        } else {
          inner_ = value;
        }
        onChanged();
      } else {
        innerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    public Builder clearInner() {
      if (innerBuilder_ == null) {
        inner_ = null;
        onChanged();
      } else {
        inner_ = null;
        innerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    public com.example.protos.InnerMessage.Builder getInnerBuilder() {
      
      onChanged();
      return getInnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    public com.example.protos.InnerMessageOrBuilder getInnerOrBuilder() {
      if (innerBuilder_ != null) {
        return innerBuilder_.getMessageOrBuilder();
      } else {
        return inner_ == null ?
            com.example.protos.InnerMessage.getDefaultInstance() : inner_;
      }
    }
    /**
     * <code>.com.example.InnerMessage inner = 18;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.protos.InnerMessage, com.example.protos.InnerMessage.Builder, com.example.protos.InnerMessageOrBuilder> 
        getInnerFieldBuilder() {
      if (innerBuilder_ == null) {
        innerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.protos.InnerMessage, com.example.protos.InnerMessage.Builder, com.example.protos.InnerMessageOrBuilder>(
                getInner(),
                getParentForChildren(),
                isClean());
        inner_ = null;
      }
      return innerBuilder_;
    }

    private com.google.protobuf.Timestamp eventTimestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     * @return Whether the eventTimestamp field is set.
     */
    public boolean hasEventTimestamp() {
      return eventTimestampBuilder_ != null || eventTimestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     * @return The eventTimestamp.
     */
    public com.google.protobuf.Timestamp getEventTimestamp() {
      if (eventTimestampBuilder_ == null) {
        return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
      } else {
        return eventTimestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    public Builder setEventTimestamp(com.google.protobuf.Timestamp value) {
      if (eventTimestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventTimestamp_ = value;
        onChanged();
      } else {
        eventTimestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    public Builder setEventTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (eventTimestampBuilder_ == null) {
        eventTimestamp_ = builderForValue.build();
        onChanged();
      } else {
        eventTimestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    public Builder mergeEventTimestamp(com.google.protobuf.Timestamp value) {
      if (eventTimestampBuilder_ == null) {
        if (eventTimestamp_ != null) {
          eventTimestamp_ =
            com.google.protobuf.Timestamp.newBuilder(eventTimestamp_).mergeFrom(value).buildPartial();
        } else {
          eventTimestamp_ = value;
        }
        onChanged();
      } else {
        eventTimestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    public Builder clearEventTimestamp() {
      if (eventTimestampBuilder_ == null) {
        eventTimestamp_ = null;
        onChanged();
      } else {
        eventTimestamp_ = null;
        eventTimestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEventTimestampBuilder() {
      
      onChanged();
      return getEventTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
      if (eventTimestampBuilder_ != null) {
        return eventTimestampBuilder_.getMessageOrBuilder();
      } else {
        return eventTimestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEventTimestampFieldBuilder() {
      if (eventTimestampBuilder_ == null) {
        eventTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEventTimestamp(),
                getParentForChildren(),
                isClean());
        eventTimestamp_ = null;
      }
      return eventTimestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.AllTypesMessage)
  }

  // @@protoc_insertion_point(class_scope:com.example.AllTypesMessage)
  private static final com.example.protos.AllTypesMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protos.AllTypesMessage();
  }

  public static com.example.protos.AllTypesMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllTypesMessage>
      PARSER = new com.google.protobuf.AbstractParser<AllTypesMessage>() {
    @java.lang.Override
    public AllTypesMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllTypesMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllTypesMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllTypesMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protos.AllTypesMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

