// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

public interface AllTypesMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.AllTypesMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double double = 1;</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <code>float float = 2;</code>
   * @return The float.
   */
  float getFloat();

  /**
   * <code>int32 integer = 3;</code>
   * @return The integer.
   */
  int getInteger();

  /**
   * <code>int64 long = 4;</code>
   * @return The long.
   */
  long getLong();

  /**
   * <code>uint32 uinteger = 5;</code>
   * @return The uinteger.
   */
  int getUinteger();

  /**
   * <code>uint64 ulong = 6;</code>
   * @return The ulong.
   */
  long getUlong();

  /**
   * <code>sint32 sinteger = 7;</code>
   * @return The sinteger.
   */
  int getSinteger();

  /**
   * <code>sint64 slong = 8;</code>
   * @return The slong.
   */
  long getSlong();

  /**
   * <code>fixed32 finteger = 9;</code>
   * @return The finteger.
   */
  int getFinteger();

  /**
   * <code>fixed64 flong = 10;</code>
   * @return The flong.
   */
  long getFlong();

  /**
   * <code>sfixed32 sfinteger = 11;</code>
   * @return The sfinteger.
   */
  int getSfinteger();

  /**
   * <code>sfixed64 sflong = 13;</code>
   * @return The sflong.
   */
  long getSflong();

  /**
   * <code>bool bool = 14;</code>
   * @return The bool.
   */
  boolean getBool();

  /**
   * <code>string string = 15;</code>
   * @return The string.
   */
  java.lang.String getString();
  /**
   * <code>string string = 15;</code>
   * @return The bytes for string.
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <code>bytes bytes = 16;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMap();
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMapMap();
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */

  java.lang.String getMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; map = 17;</code>
   */

  java.lang.String getMapOrThrow(
      java.lang.String key);

  /**
   * <code>.com.example.InnerMessage inner = 18;</code>
   * @return Whether the inner field is set.
   */
  boolean hasInner();
  /**
   * <code>.com.example.InnerMessage inner = 18;</code>
   * @return The inner.
   */
  com.example.protos.InnerMessage getInner();
  /**
   * <code>.com.example.InnerMessage inner = 18;</code>
   */
  com.example.protos.InnerMessageOrBuilder getInnerOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
   * @return Whether the eventTimestamp field is set.
   */
  boolean hasEventTimestamp();
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
   * @return The eventTimestamp.
   */
  com.google.protobuf.Timestamp getEventTimestamp();
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 19;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder();
}
