// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

/**
 * Protobuf type {@code com.example.InnerMessage}
 */
public final class InnerMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.InnerMessage)
    InnerMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InnerMessage.newBuilder() to construct.
  private InnerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InnerMessage() {
    double_ = emptyDoubleList();
    float_ = emptyFloatList();
    integer_ = emptyIntList();
    long_ = emptyLongList();
    enum_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InnerMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InnerMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              double_ = newDoubleList();
              mutable_bitField0_ |= 0x00000001;
            }
            double_.addDouble(input.readDouble());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              double_ = newDoubleList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              double_.addDouble(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 21: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              float_ = newFloatList();
              mutable_bitField0_ |= 0x00000002;
            }
            float_.addFloat(input.readFloat());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              float_ = newFloatList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              float_.addFloat(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              integer_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            integer_.addInt(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              integer_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              integer_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              long_ = newLongList();
              mutable_bitField0_ |= 0x00000008;
            }
            long_.addLong(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
              long_ = newLongList();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              long_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            enum_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        double_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        float_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        integer_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        long_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protos.Source.internal_static_com_example_InnerMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protos.Source.internal_static_com_example_InnerMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protos.InnerMessage.class, com.example.protos.InnerMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code com.example.InnerMessage.Enum}
   */
  public enum Enum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>zero = 0;</code>
     */
    zero(0),
    /**
     * <code>one = 1;</code>
     */
    one(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>zero = 0;</code>
     */
    public static final int zero_VALUE = 0;
    /**
     * <code>one = 1;</code>
     */
    public static final int one_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Enum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Enum forNumber(int value) {
      switch (value) {
        case 0: return zero;
        case 1: return one;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Enum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Enum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Enum>() {
            public Enum findValueByNumber(int number) {
              return Enum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.protos.InnerMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Enum[] VALUES = values();

    public static Enum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Enum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.example.InnerMessage.Enum)
  }

  public static final int DOUBLE_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.DoubleList double_;
  /**
   * <code>repeated double double = 1;</code>
   * @return A list containing the double.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getDoubleList() {
    return double_;
  }
  /**
   * <code>repeated double double = 1;</code>
   * @return The count of double.
   */
  public int getDoubleCount() {
    return double_.size();
  }
  /**
   * <code>repeated double double = 1;</code>
   * @param index The index of the element to return.
   * @return The double at the given index.
   */
  public double getDouble(int index) {
    return double_.getDouble(index);
  }
  private int doubleMemoizedSerializedSize = -1;

  public static final int FLOAT_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.FloatList float_;
  /**
   * <code>repeated float float = 2;</code>
   * @return A list containing the float.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getFloatList() {
    return float_;
  }
  /**
   * <code>repeated float float = 2;</code>
   * @return The count of float.
   */
  public int getFloatCount() {
    return float_.size();
  }
  /**
   * <code>repeated float float = 2;</code>
   * @param index The index of the element to return.
   * @return The float at the given index.
   */
  public float getFloat(int index) {
    return float_.getFloat(index);
  }
  private int floatMemoizedSerializedSize = -1;

  public static final int INTEGER_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList integer_;
  /**
   * <code>repeated int32 integer = 3;</code>
   * @return A list containing the integer.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getIntegerList() {
    return integer_;
  }
  /**
   * <code>repeated int32 integer = 3;</code>
   * @return The count of integer.
   */
  public int getIntegerCount() {
    return integer_.size();
  }
  /**
   * <code>repeated int32 integer = 3;</code>
   * @param index The index of the element to return.
   * @return The integer at the given index.
   */
  public int getInteger(int index) {
    return integer_.getInt(index);
  }
  private int integerMemoizedSerializedSize = -1;

  public static final int LONG_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList long_;
  /**
   * <code>repeated int64 long = 4;</code>
   * @return A list containing the long.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getLongList() {
    return long_;
  }
  /**
   * <code>repeated int64 long = 4;</code>
   * @return The count of long.
   */
  public int getLongCount() {
    return long_.size();
  }
  /**
   * <code>repeated int64 long = 4;</code>
   * @param index The index of the element to return.
   * @return The long at the given index.
   */
  public long getLong(int index) {
    return long_.getLong(index);
  }
  private int longMemoizedSerializedSize = -1;

  public static final int ENUM_FIELD_NUMBER = 5;
  private int enum_;
  /**
   * <code>.com.example.InnerMessage.Enum enum = 5;</code>
   * @return The enum numeric value on the wire for enum.
   */
  @java.lang.Override public int getEnumValue() {
    return enum_;
  }
  /**
   * <code>.com.example.InnerMessage.Enum enum = 5;</code>
   * @return The enum.
   */
  @java.lang.Override public com.example.protos.InnerMessage.Enum getEnum() {
    @SuppressWarnings("deprecation")
    com.example.protos.InnerMessage.Enum result = com.example.protos.InnerMessage.Enum.valueOf(enum_);
    return result == null ? com.example.protos.InnerMessage.Enum.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getDoubleList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(doubleMemoizedSerializedSize);
    }
    for (int i = 0; i < double_.size(); i++) {
      output.writeDoubleNoTag(double_.getDouble(i));
    }
    if (getFloatList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(floatMemoizedSerializedSize);
    }
    for (int i = 0; i < float_.size(); i++) {
      output.writeFloatNoTag(float_.getFloat(i));
    }
    if (getIntegerList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(integerMemoizedSerializedSize);
    }
    for (int i = 0; i < integer_.size(); i++) {
      output.writeInt32NoTag(integer_.getInt(i));
    }
    if (getLongList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(longMemoizedSerializedSize);
    }
    for (int i = 0; i < long_.size(); i++) {
      output.writeInt64NoTag(long_.getLong(i));
    }
    if (enum_ != com.example.protos.InnerMessage.Enum.zero.getNumber()) {
      output.writeEnum(5, enum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getDoubleList().size();
      size += dataSize;
      if (!getDoubleList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      doubleMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 4 * getFloatList().size();
      size += dataSize;
      if (!getFloatList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      floatMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < integer_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(integer_.getInt(i));
      }
      size += dataSize;
      if (!getIntegerList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      integerMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < long_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(long_.getLong(i));
      }
      size += dataSize;
      if (!getLongList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      longMemoizedSerializedSize = dataSize;
    }
    if (enum_ != com.example.protos.InnerMessage.Enum.zero.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, enum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protos.InnerMessage)) {
      return super.equals(obj);
    }
    com.example.protos.InnerMessage other = (com.example.protos.InnerMessage) obj;

    if (!getDoubleList()
        .equals(other.getDoubleList())) return false;
    if (!getFloatList()
        .equals(other.getFloatList())) return false;
    if (!getIntegerList()
        .equals(other.getIntegerList())) return false;
    if (!getLongList()
        .equals(other.getLongList())) return false;
    if (enum_ != other.enum_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDoubleCount() > 0) {
      hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
      hash = (53 * hash) + getDoubleList().hashCode();
    }
    if (getFloatCount() > 0) {
      hash = (37 * hash) + FLOAT_FIELD_NUMBER;
      hash = (53 * hash) + getFloatList().hashCode();
    }
    if (getIntegerCount() > 0) {
      hash = (37 * hash) + INTEGER_FIELD_NUMBER;
      hash = (53 * hash) + getIntegerList().hashCode();
    }
    if (getLongCount() > 0) {
      hash = (37 * hash) + LONG_FIELD_NUMBER;
      hash = (53 * hash) + getLongList().hashCode();
    }
    hash = (37 * hash) + ENUM_FIELD_NUMBER;
    hash = (53 * hash) + enum_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protos.InnerMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.InnerMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.InnerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.InnerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.InnerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.InnerMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.InnerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.InnerMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.InnerMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.protos.InnerMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.InnerMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.InnerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protos.InnerMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.InnerMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.InnerMessage)
      com.example.protos.InnerMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protos.Source.internal_static_com_example_InnerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protos.Source.internal_static_com_example_InnerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protos.InnerMessage.class, com.example.protos.InnerMessage.Builder.class);
    }

    // Construct using com.example.protos.InnerMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      double_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      float_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      integer_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      long_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000008);
      enum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protos.Source.internal_static_com_example_InnerMessage_descriptor;
    }

    @java.lang.Override
    public com.example.protos.InnerMessage getDefaultInstanceForType() {
      return com.example.protos.InnerMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protos.InnerMessage build() {
      com.example.protos.InnerMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protos.InnerMessage buildPartial() {
      com.example.protos.InnerMessage result = new com.example.protos.InnerMessage(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        double_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.double_ = double_;
      if (((bitField0_ & 0x00000002) != 0)) {
        float_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.float_ = float_;
      if (((bitField0_ & 0x00000004) != 0)) {
        integer_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.integer_ = integer_;
      if (((bitField0_ & 0x00000008) != 0)) {
        long_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.long_ = long_;
      result.enum_ = enum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protos.InnerMessage) {
        return mergeFrom((com.example.protos.InnerMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protos.InnerMessage other) {
      if (other == com.example.protos.InnerMessage.getDefaultInstance()) return this;
      if (!other.double_.isEmpty()) {
        if (double_.isEmpty()) {
          double_ = other.double_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureDoubleIsMutable();
          double_.addAll(other.double_);
        }
        onChanged();
      }
      if (!other.float_.isEmpty()) {
        if (float_.isEmpty()) {
          float_ = other.float_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureFloatIsMutable();
          float_.addAll(other.float_);
        }
        onChanged();
      }
      if (!other.integer_.isEmpty()) {
        if (integer_.isEmpty()) {
          integer_ = other.integer_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureIntegerIsMutable();
          integer_.addAll(other.integer_);
        }
        onChanged();
      }
      if (!other.long_.isEmpty()) {
        if (long_.isEmpty()) {
          long_ = other.long_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureLongIsMutable();
          long_.addAll(other.long_);
        }
        onChanged();
      }
      if (other.enum_ != 0) {
        setEnumValue(other.getEnumValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.protos.InnerMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.protos.InnerMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.DoubleList double_ = emptyDoubleList();
    private void ensureDoubleIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        double_ = mutableCopy(double_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated double double = 1;</code>
     * @return A list containing the double.
     */
    public java.util.List<java.lang.Double>
        getDoubleList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(double_) : double_;
    }
    /**
     * <code>repeated double double = 1;</code>
     * @return The count of double.
     */
    public int getDoubleCount() {
      return double_.size();
    }
    /**
     * <code>repeated double double = 1;</code>
     * @param index The index of the element to return.
     * @return The double at the given index.
     */
    public double getDouble(int index) {
      return double_.getDouble(index);
    }
    /**
     * <code>repeated double double = 1;</code>
     * @param index The index to set the value at.
     * @param value The double to set.
     * @return This builder for chaining.
     */
    public Builder setDouble(
        int index, double value) {
      ensureDoubleIsMutable();
      double_.setDouble(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double double = 1;</code>
     * @param value The double to add.
     * @return This builder for chaining.
     */
    public Builder addDouble(double value) {
      ensureDoubleIsMutable();
      double_.addDouble(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double double = 1;</code>
     * @param values The double to add.
     * @return This builder for chaining.
     */
    public Builder addAllDouble(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureDoubleIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, double_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double double = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDouble() {
      double_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList float_ = emptyFloatList();
    private void ensureFloatIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        float_ = mutableCopy(float_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated float float = 2;</code>
     * @return A list containing the float.
     */
    public java.util.List<java.lang.Float>
        getFloatList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(float_) : float_;
    }
    /**
     * <code>repeated float float = 2;</code>
     * @return The count of float.
     */
    public int getFloatCount() {
      return float_.size();
    }
    /**
     * <code>repeated float float = 2;</code>
     * @param index The index of the element to return.
     * @return The float at the given index.
     */
    public float getFloat(int index) {
      return float_.getFloat(index);
    }
    /**
     * <code>repeated float float = 2;</code>
     * @param index The index to set the value at.
     * @param value The float to set.
     * @return This builder for chaining.
     */
    public Builder setFloat(
        int index, float value) {
      ensureFloatIsMutable();
      float_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float float = 2;</code>
     * @param value The float to add.
     * @return This builder for chaining.
     */
    public Builder addFloat(float value) {
      ensureFloatIsMutable();
      float_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float float = 2;</code>
     * @param values The float to add.
     * @return This builder for chaining.
     */
    public Builder addAllFloat(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureFloatIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, float_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float float = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat() {
      float_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList integer_ = emptyIntList();
    private void ensureIntegerIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        integer_ = mutableCopy(integer_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @return A list containing the integer.
     */
    public java.util.List<java.lang.Integer>
        getIntegerList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(integer_) : integer_;
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @return The count of integer.
     */
    public int getIntegerCount() {
      return integer_.size();
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @param index The index of the element to return.
     * @return The integer at the given index.
     */
    public int getInteger(int index) {
      return integer_.getInt(index);
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @param index The index to set the value at.
     * @param value The integer to set.
     * @return This builder for chaining.
     */
    public Builder setInteger(
        int index, int value) {
      ensureIntegerIsMutable();
      integer_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @param value The integer to add.
     * @return This builder for chaining.
     */
    public Builder addInteger(int value) {
      ensureIntegerIsMutable();
      integer_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @param values The integer to add.
     * @return This builder for chaining.
     */
    public Builder addAllInteger(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureIntegerIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, integer_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 integer = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteger() {
      integer_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList long_ = emptyLongList();
    private void ensureLongIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        long_ = mutableCopy(long_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @return A list containing the long.
     */
    public java.util.List<java.lang.Long>
        getLongList() {
      return ((bitField0_ & 0x00000008) != 0) ?
               java.util.Collections.unmodifiableList(long_) : long_;
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @return The count of long.
     */
    public int getLongCount() {
      return long_.size();
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @param index The index of the element to return.
     * @return The long at the given index.
     */
    public long getLong(int index) {
      return long_.getLong(index);
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @param index The index to set the value at.
     * @param value The long to set.
     * @return This builder for chaining.
     */
    public Builder setLong(
        int index, long value) {
      ensureLongIsMutable();
      long_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @param value The long to add.
     * @return This builder for chaining.
     */
    public Builder addLong(long value) {
      ensureLongIsMutable();
      long_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @param values The long to add.
     * @return This builder for chaining.
     */
    public Builder addAllLong(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureLongIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, long_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 long = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLong() {
      long_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private int enum_ = 0;
    /**
     * <code>.com.example.InnerMessage.Enum enum = 5;</code>
     * @return The enum numeric value on the wire for enum.
     */
    @java.lang.Override public int getEnumValue() {
      return enum_;
    }
    /**
     * <code>.com.example.InnerMessage.Enum enum = 5;</code>
     * @param value The enum numeric value on the wire for enum to set.
     * @return This builder for chaining.
     */
    public Builder setEnumValue(int value) {
      
      enum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.InnerMessage.Enum enum = 5;</code>
     * @return The enum.
     */
    @java.lang.Override
    public com.example.protos.InnerMessage.Enum getEnum() {
      @SuppressWarnings("deprecation")
      com.example.protos.InnerMessage.Enum result = com.example.protos.InnerMessage.Enum.valueOf(enum_);
      return result == null ? com.example.protos.InnerMessage.Enum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.example.InnerMessage.Enum enum = 5;</code>
     * @param value The enum to set.
     * @return This builder for chaining.
     */
    public Builder setEnum(com.example.protos.InnerMessage.Enum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      enum_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.InnerMessage.Enum enum = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnum() {
      
      enum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.InnerMessage)
  }

  // @@protoc_insertion_point(class_scope:com.example.InnerMessage)
  private static final com.example.protos.InnerMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protos.InnerMessage();
  }

  public static com.example.protos.InnerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InnerMessage>
      PARSER = new com.google.protobuf.AbstractParser<InnerMessage>() {
    @java.lang.Override
    public InnerMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InnerMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InnerMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InnerMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protos.InnerMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

