// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

public interface InnerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.InnerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double double = 1;</code>
   * @return A list containing the double.
   */
  java.util.List<java.lang.Double> getDoubleList();
  /**
   * <code>repeated double double = 1;</code>
   * @return The count of double.
   */
  int getDoubleCount();
  /**
   * <code>repeated double double = 1;</code>
   * @param index The index of the element to return.
   * @return The double at the given index.
   */
  double getDouble(int index);

  /**
   * <code>repeated float float = 2;</code>
   * @return A list containing the float.
   */
  java.util.List<java.lang.Float> getFloatList();
  /**
   * <code>repeated float float = 2;</code>
   * @return The count of float.
   */
  int getFloatCount();
  /**
   * <code>repeated float float = 2;</code>
   * @param index The index of the element to return.
   * @return The float at the given index.
   */
  float getFloat(int index);

  /**
   * <code>repeated int32 integer = 3;</code>
   * @return A list containing the integer.
   */
  java.util.List<java.lang.Integer> getIntegerList();
  /**
   * <code>repeated int32 integer = 3;</code>
   * @return The count of integer.
   */
  int getIntegerCount();
  /**
   * <code>repeated int32 integer = 3;</code>
   * @param index The index of the element to return.
   * @return The integer at the given index.
   */
  int getInteger(int index);

  /**
   * <code>repeated int64 long = 4;</code>
   * @return A list containing the long.
   */
  java.util.List<java.lang.Long> getLongList();
  /**
   * <code>repeated int64 long = 4;</code>
   * @return The count of long.
   */
  int getLongCount();
  /**
   * <code>repeated int64 long = 4;</code>
   * @param index The index of the element to return.
   * @return The long at the given index.
   */
  long getLong(int index);

  /**
   * <code>.com.example.InnerMessage.Enum enum = 5;</code>
   * @return The enum numeric value on the wire for enum.
   */
  int getEnumValue();
  /**
   * <code>.com.example.InnerMessage.Enum enum = 5;</code>
   * @return The enum.
   */
  com.example.protos.InnerMessage.Enum getEnum();
}
