// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

/**
 * Protobuf type {@code com.example.TestMessage}
 */
public final class TestMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.TestMessage)
    TestMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestMessage.newBuilder() to construct.
  private TestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestMessage() {
    vehicleType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            s2Id_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            vehicleType_ = rawValue;
            break;
          }
          case 24: {

            uniqueDrivers_ = input.readInt64();
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (eventTimestamp_ != null) {
              subBuilder = eventTimestamp_.toBuilder();
            }
            eventTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(eventTimestamp_);
              eventTimestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protos.Source.internal_static_com_example_TestMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protos.Source.internal_static_com_example_TestMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protos.TestMessage.class, com.example.protos.TestMessage.Builder.class);
  }

  public static final int S2_ID_FIELD_NUMBER = 1;
  private long s2Id_;
  /**
   * <code>int64 s2_id = 1;</code>
   * @return The s2Id.
   */
  @java.lang.Override
  public long getS2Id() {
    return s2Id_;
  }

  public static final int VEHICLE_TYPE_FIELD_NUMBER = 2;
  private int vehicleType_;
  /**
   * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
   * @return The enum numeric value on the wire for vehicleType.
   */
  @java.lang.Override public int getVehicleTypeValue() {
    return vehicleType_;
  }
  /**
   * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
   * @return The vehicleType.
   */
  @java.lang.Override public com.example.protos.VehicleType.Enum getVehicleType() {
    @SuppressWarnings("deprecation")
    com.example.protos.VehicleType.Enum result = com.example.protos.VehicleType.Enum.valueOf(vehicleType_);
    return result == null ? com.example.protos.VehicleType.Enum.UNRECOGNIZED : result;
  }

  public static final int UNIQUE_DRIVERS_FIELD_NUMBER = 3;
  private long uniqueDrivers_;
  /**
   * <code>int64 unique_drivers = 3;</code>
   * @return The uniqueDrivers.
   */
  @java.lang.Override
  public long getUniqueDrivers() {
    return uniqueDrivers_;
  }

  public static final int EVENT_TIMESTAMP_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp eventTimestamp_;
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
   * @return Whether the eventTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasEventTimestamp() {
    return eventTimestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
   * @return The eventTimestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEventTimestamp() {
    return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
    return getEventTimestamp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (s2Id_ != 0L) {
      output.writeInt64(1, s2Id_);
    }
    if (vehicleType_ != com.example.protos.VehicleType.Enum.UNKNOWN.getNumber()) {
      output.writeEnum(2, vehicleType_);
    }
    if (uniqueDrivers_ != 0L) {
      output.writeInt64(3, uniqueDrivers_);
    }
    if (eventTimestamp_ != null) {
      output.writeMessage(4, getEventTimestamp());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (s2Id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, s2Id_);
    }
    if (vehicleType_ != com.example.protos.VehicleType.Enum.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, vehicleType_);
    }
    if (uniqueDrivers_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, uniqueDrivers_);
    }
    if (eventTimestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEventTimestamp());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protos.TestMessage)) {
      return super.equals(obj);
    }
    com.example.protos.TestMessage other = (com.example.protos.TestMessage) obj;

    if (getS2Id()
        != other.getS2Id()) return false;
    if (vehicleType_ != other.vehicleType_) return false;
    if (getUniqueDrivers()
        != other.getUniqueDrivers()) return false;
    if (hasEventTimestamp() != other.hasEventTimestamp()) return false;
    if (hasEventTimestamp()) {
      if (!getEventTimestamp()
          .equals(other.getEventTimestamp())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + S2_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getS2Id());
    hash = (37 * hash) + VEHICLE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + vehicleType_;
    hash = (37 * hash) + UNIQUE_DRIVERS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUniqueDrivers());
    if (hasEventTimestamp()) {
      hash = (37 * hash) + EVENT_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getEventTimestamp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protos.TestMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.TestMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.TestMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.TestMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.TestMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protos.TestMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protos.TestMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.TestMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.TestMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.protos.TestMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protos.TestMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protos.TestMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protos.TestMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.TestMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.TestMessage)
      com.example.protos.TestMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protos.Source.internal_static_com_example_TestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protos.Source.internal_static_com_example_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protos.TestMessage.class, com.example.protos.TestMessage.Builder.class);
    }

    // Construct using com.example.protos.TestMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      s2Id_ = 0L;

      vehicleType_ = 0;

      uniqueDrivers_ = 0L;

      if (eventTimestampBuilder_ == null) {
        eventTimestamp_ = null;
      } else {
        eventTimestamp_ = null;
        eventTimestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protos.Source.internal_static_com_example_TestMessage_descriptor;
    }

    @java.lang.Override
    public com.example.protos.TestMessage getDefaultInstanceForType() {
      return com.example.protos.TestMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protos.TestMessage build() {
      com.example.protos.TestMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protos.TestMessage buildPartial() {
      com.example.protos.TestMessage result = new com.example.protos.TestMessage(this);
      result.s2Id_ = s2Id_;
      result.vehicleType_ = vehicleType_;
      result.uniqueDrivers_ = uniqueDrivers_;
      if (eventTimestampBuilder_ == null) {
        result.eventTimestamp_ = eventTimestamp_;
      } else {
        result.eventTimestamp_ = eventTimestampBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protos.TestMessage) {
        return mergeFrom((com.example.protos.TestMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protos.TestMessage other) {
      if (other == com.example.protos.TestMessage.getDefaultInstance()) return this;
      if (other.getS2Id() != 0L) {
        setS2Id(other.getS2Id());
      }
      if (other.vehicleType_ != 0) {
        setVehicleTypeValue(other.getVehicleTypeValue());
      }
      if (other.getUniqueDrivers() != 0L) {
        setUniqueDrivers(other.getUniqueDrivers());
      }
      if (other.hasEventTimestamp()) {
        mergeEventTimestamp(other.getEventTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.protos.TestMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.protos.TestMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long s2Id_ ;
    /**
     * <code>int64 s2_id = 1;</code>
     * @return The s2Id.
     */
    @java.lang.Override
    public long getS2Id() {
      return s2Id_;
    }
    /**
     * <code>int64 s2_id = 1;</code>
     * @param value The s2Id to set.
     * @return This builder for chaining.
     */
    public Builder setS2Id(long value) {
      
      s2Id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 s2_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearS2Id() {
      
      s2Id_ = 0L;
      onChanged();
      return this;
    }

    private int vehicleType_ = 0;
    /**
     * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
     * @return The enum numeric value on the wire for vehicleType.
     */
    @java.lang.Override public int getVehicleTypeValue() {
      return vehicleType_;
    }
    /**
     * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
     * @param value The enum numeric value on the wire for vehicleType to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleTypeValue(int value) {
      
      vehicleType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
     * @return The vehicleType.
     */
    @java.lang.Override
    public com.example.protos.VehicleType.Enum getVehicleType() {
      @SuppressWarnings("deprecation")
      com.example.protos.VehicleType.Enum result = com.example.protos.VehicleType.Enum.valueOf(vehicleType_);
      return result == null ? com.example.protos.VehicleType.Enum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
     * @param value The vehicleType to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleType(com.example.protos.VehicleType.Enum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      vehicleType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVehicleType() {
      
      vehicleType_ = 0;
      onChanged();
      return this;
    }

    private long uniqueDrivers_ ;
    /**
     * <code>int64 unique_drivers = 3;</code>
     * @return The uniqueDrivers.
     */
    @java.lang.Override
    public long getUniqueDrivers() {
      return uniqueDrivers_;
    }
    /**
     * <code>int64 unique_drivers = 3;</code>
     * @param value The uniqueDrivers to set.
     * @return This builder for chaining.
     */
    public Builder setUniqueDrivers(long value) {
      
      uniqueDrivers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 unique_drivers = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUniqueDrivers() {
      
      uniqueDrivers_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp eventTimestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     * @return Whether the eventTimestamp field is set.
     */
    public boolean hasEventTimestamp() {
      return eventTimestampBuilder_ != null || eventTimestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     * @return The eventTimestamp.
     */
    public com.google.protobuf.Timestamp getEventTimestamp() {
      if (eventTimestampBuilder_ == null) {
        return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
      } else {
        return eventTimestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    public Builder setEventTimestamp(com.google.protobuf.Timestamp value) {
      if (eventTimestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventTimestamp_ = value;
        onChanged();
      } else {
        eventTimestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    public Builder setEventTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (eventTimestampBuilder_ == null) {
        eventTimestamp_ = builderForValue.build();
        onChanged();
      } else {
        eventTimestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    public Builder mergeEventTimestamp(com.google.protobuf.Timestamp value) {
      if (eventTimestampBuilder_ == null) {
        if (eventTimestamp_ != null) {
          eventTimestamp_ =
            com.google.protobuf.Timestamp.newBuilder(eventTimestamp_).mergeFrom(value).buildPartial();
        } else {
          eventTimestamp_ = value;
        }
        onChanged();
      } else {
        eventTimestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    public Builder clearEventTimestamp() {
      if (eventTimestampBuilder_ == null) {
        eventTimestamp_ = null;
        onChanged();
      } else {
        eventTimestamp_ = null;
        eventTimestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEventTimestampBuilder() {
      
      onChanged();
      return getEventTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
      if (eventTimestampBuilder_ != null) {
        return eventTimestampBuilder_.getMessageOrBuilder();
      } else {
        return eventTimestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEventTimestampFieldBuilder() {
      if (eventTimestampBuilder_ == null) {
        eventTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEventTimestamp(),
                getParentForChildren(),
                isClean());
        eventTimestamp_ = null;
      }
      return eventTimestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.TestMessage)
  }

  // @@protoc_insertion_point(class_scope:com.example.TestMessage)
  private static final com.example.protos.TestMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protos.TestMessage();
  }

  public static com.example.protos.TestMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestMessage>
      PARSER = new com.google.protobuf.AbstractParser<TestMessage>() {
    @java.lang.Override
    public TestMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protos.TestMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

