// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

public interface TestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.TestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 s2_id = 1;</code>
   * @return The s2Id.
   */
  long getS2Id();

  /**
   * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
   * @return The enum numeric value on the wire for vehicleType.
   */
  int getVehicleTypeValue();
  /**
   * <code>.com.example.VehicleType.Enum vehicle_type = 2;</code>
   * @return The vehicleType.
   */
  com.example.protos.VehicleType.Enum getVehicleType();

  /**
   * <code>int64 unique_drivers = 3;</code>
   * @return The uniqueDrivers.
   */
  long getUniqueDrivers();

  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
   * @return Whether the eventTimestamp field is set.
   */
  boolean hasEventTimestamp();
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
   * @return The eventTimestamp.
   */
  com.google.protobuf.Timestamp getEventTimestamp();
  /**
   * <code>.google.protobuf.Timestamp event_timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder();
}
