// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

package com.example.protos;

public interface VehicleTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.VehicleType)
    com.google.protobuf.MessageOrBuilder {
}
