name: test-suite

on: [push, pull_request]

jobs:
  unit-test-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.7
      - name: include submodule
        run: git submodule update --init
#       - name: Get pip cache dir
#         id: pip-cache
#         run: |
#           echo "::set-output name=dir::$(pip cache dir)"
#       - name: pip cache
#         uses: actions/cache@v2
#         with:
#           path: |
#             ${{ steps.pip-cache.outputs.dir }}
#             /opt/hostedtoolcache/Python
#             /Users/runner/hostedtoolcache/Python
#           key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-pip-${{ hashFiles('**/setup.py') }}
#           restore-keys: |
#             ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-pip-
      - name: Install pip-tools
        run: pip install pip-tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install db-dtypes
          make install-python-ci-dependencies
      - name: Run Feast unit tests
        run: FEAST_USAGE=False IS_TEST=True python -m pytest -n 8 feast/sdk/python/tests
